/// register user
export const REGISTER_CREATE_REQUEST = 'REGISTER_CREATE_REQUEST';
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS'
export const REGISTER_CREATE_FAIL = 'REGISTER_CREATE_FAIL'

//update admin profile
export const UPDATE_ADMIN_PROFILE_REQUEST = 'UPDATE_ADMIN_PROFILE_REQUEST';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_ADMIN_PROFILE_FAIL = 'UPDATE_ADMIN_PROFILE_FAIL';

/// login user
export const LOGIN_CREATE_REQUEST = 'LOGIN_CREATE_REQUEST';
export const LOGIN_CREATE_SUCCESS = 'LOGIN_CREATE_SUCCESS';
export const LOGIN_CREATE_FAIL = 'LOGIN_CREATE_FAIL';

///otp send for register user
export const OTP_SEND_REQUEST = 'OTP_SEND_REQUEST';
export const OTP_SEND_SUCCESS = 'OTP_SEND_SUCCESS';
export const OTP_SEND_FAIL = 'OTP_SEND_FAIL';

//forget password otp send
export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

///forget password confirm
export const FORGET_PASSWORD_CONFIRM_REQUEST = 'FORGET_PASSWORD_CONFIRM_REQUEST';
export const FORGET_PASSWORD_CONFIRM_SUCCESS = 'FORGET_PASSWORD_CONFIRM_SUCCESS';
export const FORGET_PASSWORD_CONFIRM_FAIL = 'FORGET_PASSWORD_CONFIRM_FAIL';

///refresh user token
export const USER_TOKEN_REFRESH_REQUEST = 'USER_TOKEN_REFRESH_REQUEST';
export const USER_TOKEN_REFRESH_SUCCESS = 'USER_TOKEN_REFRESH_SUCCESS';
export const USER_TOKEN_REFRESH_FAIL = 'USER_TOKEN_REFRESH_FAIL';


///logout user
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';

//refresh user reducers
export const REFRESH_LODDER_AUTH = 'REFRESH_LODDER_AUTH';