
//creat worker
export const CREATE_SEND_OTP_WORKERS_REQUEST = 'CREATE_SEND_OTP_WORKERS_REQUEST';
export const CREATE_SEND_OTP_WORKERS_SUCCESS = 'CREATE_SEND_OTP_WORKERS_SUCCESS';
export const CREATE_SEND_OTP_WORKERS_FAIL = 'CREATE_SEND_OTP_WORKERS_FAIL';
//worker create confrim
export const CREATE_CONFRIM_WORKERS_FAIL = 'CREATE_CONFRIM_WORKERS_FAIL'
export const CREATE_CONFRIM_WORKERS_SUCCESS = 'CREATE_CONFRIM_WORKERS_SUCCESS'
export const CREATE_CONFRIM_WORKERS_REQUEST = 'CREATE_CONFRIM_WORKERS_REQUEST';

//get all workers
export const GET_ALL_WORKERS_REQUEST = 'GET_ALL_WORKERS_REQUEST';
export const GET_ALL_WORKERS_SUCCESS = 'GET_ALL_WORKERS_SUCCESS';
export const GET_ALL_WORKERS_FAIL = 'GET_ALL_WORKERS_FAIL';




//get single worker
export const GET_SINGLE_WORKER_SUCCESS = 'GET_SINGLE_WORKER_SUCCESS';
export const GET_SINGLE_WORKER_REQUEST = 'GET_SINGLE_WORKER_REQUEST';
export const GET_SINGLE_WORKER_FAIL = 'GET_SINGLE_WORKER_FAIL';

///delete worker
export const DELETE_WORKER_REQUEST = 'DELETE_WORKER_REQUEST';
export const DELETE_WORKER_SUCCESS = 'DELETE_WORKER_SUCCESS';
export const DELETE_WORKER_FAIL = 'DELETE_WORKER_FAIL';

///update worker profile
export const UPDATE_WORKER_PROFILE_REQUEST = 'UPDATE_WORKER_PROFILE_REQUEST';
export const UPDATE_WORKER_PROFILE_SUCCESS = 'UPDATE_WORKER_PROFILE_SUCCESS';
export const UPDATE_WORKER_PROFILE_FAIL = 'UPDATE_WORKER_PROFILE_FAIL';

///refresh worker reducers
export const REFRESH_WORKER_REQUEST = 'REFRESH_WORKER_REQUEST'


export const UPDATE_WORKER_AVATAR_PROFILE_REQUEST = 'UPDATE_WORKER_AVATAR_PROFILE_REQUEST';
export const UPDATE_WORKER_AVATAR_PROFILE_SUCCESS = 'UPDATE_WORKER_AVATAR_PROFILE_SUCCESS';
export const UPDATE_WORKER_AVATAR_PROFILE_FAIL = 'UPDATE_WORKER_AVATAR_PROFILE_FAIL';


///get all clients
export const GET_ALL_CLIENTS_REQUEST = 'GET_ALL_CLIENTS_REQUEST';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_FAIL = 'GET_ALL_CLIENTS_FAIL';
export const CLIENTS_REFRESH_REQUEST = 'CLIENTS_REFRESH_REQUEST';


///////////start services
export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL';
///create service
export const CREATE_SERVICES_REQUEST = 'CREATE_SERVICES_REQUEST';
export const CREATE_SERVICES_SUCCESS = 'CREATE_SERVICES_SUCCESS';
export const CREATE_SERVICES_FAIL = 'CREATE_SERVICES_FAIL';
///update service
export const UPDATE_SERVICES_REQUEST = 'UPDATE_SERVICES_REQUEST';
export const UPDATE_SERVICES_SUCCESS = 'UPDATE_SERVICES_SUCCESS';
export const UPDATE_SERVICES_FAIL = 'UPDATE_SERVICES_FAIL';
export const REFRESH_SERVICES = 'REFRESH_SERVICES';
///DELETE SERVICE
export const DELETE_SERVICES_REQUEST = 'DELETE_SERVICES_REQUEST';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';
export const DELETE_SERVICES_FAIL = 'DELETE_SERVICES_FAIL';

///service discount
export const SERVICE_DISCOUNT_REQUEST = 'SERVICE_DISCOUNT_REQUEST';
export const SERVICE_DISCOUNT_SUCCESS = 'SERVICE_DISCOUNT_SUCCESS';
export const SERVICE_DISCOUNT_FAIL = 'SERVICE_DISCOUNT_FAIL';

/////////start service categories
export const GET_ALL_CATEGORY_SERVICES_SUCCESS = 'GET_ALL_CATEGORY_SERVICES_SUCCESS';
export const GET_ALL_CATEGORY_SERVICES_FAIL = 'GET_ALL_CATEGORY_SERVICES_FAIL';
export const GET_ALL_CATEGORY_SERVICES_REQUEST = 'GET_ALL_CATEGORY_SERVICES_REQUEST';

///create categories
export const CREATE_CATEGORY_SERVICES_SUCCESS = 'CREATE_CATEGORY_SERVICES_SUCCESS';
export const CREATE_CATEGORY_SERVICES_FAIL =  'CREATE_CATEGORY_SERVICES_FAIL';
export const CREATE_CATEGORY_SERVICES_REQUEST = 'CREATE_CATEGORY_SERVICES_REQUEST';
export const REFRESH_SERVICE_CATEGORY_REQUEST = 'REFRESH_SERVICE_CATEGORY_REQUEST';

export const UPDATE_CATEGORY_SERVICES_SUCCESS = 'UPDATE_CATEGORY_SERVICES_SUCCESS';
export const UPDATE_CATEGORY_SERVICES_FAIL = 'UPDATE_CATEGORY_SERVICES_FAIL';
export const UPDATE_CATEGORY_SERVICES_REQUEST = 'UPDATE_CATEGORY_SERVICES_REQUEST';
export const DELETE_CATEGORY_SERVICES_SUCCESS = 'DELETE_CATEGORY_SERVICES_SUCCESS';
export const DELETE_CATEGORY_SERVICES_FAIL = 'DELETE_CATEGORY_SERVICES_FAIL';
export const DELETE_CATEGORY_SERVICES_REQUEST = 'DELETE_CATEGORY_SERVICES_REQUEST';

///get all payments
export const GET_ALL_PAYMENT_REQUEST = 'GET_ALL_PAYMENT_REQUEST';
export const GET_ALL_PAYMENT_SUCCESS = 'GET_ALL_PAYMENT_SUCCESS';
export const GET_ALL_PAYMENT_FAIL = 'GET_ALL_PAYMENT_FAIL';

///home pages 
export const CREATE_HOME_APPS_REQUEST = 'CREATE_HOME_APPS_REQUEST'
export const CREATE_HOME_APPS_SUCCESS = 'CREATE_HOME_APPS_SUCCESS'
export const CREATE_HOME_APPS_FAIL = 'CREATE_HOME_APPS_FAIL'
export const GET_HOME_APPS_REQUEST = 'GET_HOME_APPS_REQUEST'
export const GET_HOME_APPS_SUCCESS = 'GET_HOME_APPS_SUCCESS'
export const GET_HOME_APPS_FAIL = 'GET_HOME_APPS_FAIL'


export const CREATE_HOME_PAGE_VIDEO_REQUEST = 'CREATE_HOME_PAGE_VIDEO_REQUEST'
export const CREATE_HOME_PAGE_VIDEO_SUCCESS = 'CREATE_HOME_PAGE_VIDEO_SUCCESS'
export const CREATE_HOME_PAGE_VIDEO_FAIL = 'CREATE_HOME_PAGE_VIDEO_FAIL'
export const GET_HOME_PAGE_VIDEO_REQUEST = 'GET_HOME_PAGE_VIDEO_REQUEST'
export const GET_HOME_PAGE_VIDEO_SUCCESS = 'GET_HOME_PAGE_VIDEO_SUCCESS'
export const GET_HOME_PAGE_VIDEO_FAIL = 'GET_HOME_PAGE_VIDEO_FAIL'
export const RESET_HOME_PAGES_METHOD = 'RESET_HOME_PAGES_METHOD';


export const UPDATE_WORKER_IS_FREE_REQUEST = 'UPDATE_WORKER_IS_FREE_REQUEST';
export const UPDATE_WORKER_IS_FREE_SUCCESS = 'UPDATE_WORKER_IS_FREE_SUCCESS';
export const UPDATE_WORKER_IS_FREE_FAIL = 'UPDATE_WORKER_IS_FREE_FAIL';

///get all division
export const GET_ALL_DIVISION_REQUEST = 'GET_ALL_DIVISION_REQUEST';
export const GET_ALL_DIVISION_SUCCESS = 'GET_ALL_DIVISION_SUCCESS';
export const GET_ALL_DIVISION_FAIL = 'GET_ALL_DIVISION_FAIL';

export const GET_ALL_DISTRICT_REQUEST = 'GET_ALL_DISTRICT_REQUEST'
export const GET_ALL_DISTRICT_SUCCESS = 'GET_ALL_DISTRICT_SUCCESS'
export const GET_ALL_DISTRICT_FAIL = 'GET_ALL_DISTRICT_FAIL'
export const GET_ALL_UPAZILA_FAIL = 'GET_ALL_UPAZILA_FAIL'
export const GET_ALL_UPAZILA_REQUEST = 'GET_ALL_UPAZILA_REQUEST'
export const GET_ALL_UPAZILA_SUCCESS = 'GET_ALL_UPAZILA_SUCCESS'