export const GET_ALL_BANNERS_REQUEST = 'GET_ALL_BANNERS_REQUEST';
export const GET_ALL_BANNERS_SUCCESS = 'GET_ALL_BANNERS_SUCCESS';
export const GET_ALL_BANNERS_FAIL = 'GET_ALL_BANNERS_FAIL';

export const REFRESH_BANNER_REQUEST = 'REFRESH_BANNER_REQUEST';

export const GET_SINGLE_BANNERS_REQUEST = 'GET_SINGLE_BANNERS_REQUEST';
export const GET_SINGLE_BANNERS_SUCCESS = 'GET_SINGLE_BANNERS_SUCCESS';
export const GET_SINGLE_BANNERS_FAIL = 'GET_SINGLE_BANNERS_FAIL'

export const GET_ACTIVE_BANNER_REQUEST = 'GET_ACTIVE_BANNER_REQUEST';
export const GET_ACTIVE_BANNER_SUCCESS = 'GET_ACTIVE_BANNER_SUCCESS';
export const GET_ACTIVE_BANNER_FAIL = 'GET_ACTIVE_BANNER_FAIL';

export const CREATE_BANNERS_REQUEST = 'CREATE_BANNERS_REQUEST';
export const CREATE_BANNERS_SUCCESS = 'CREATE_BANNERS_SUCCESS';
export const CREATE_BANNERS_FAIL = 'CREATE_BANNERS_FAIL'


export const UPDATE_BANNERS_REQUEST = 'UPDATE_BANNERS_REQUEST';
export const UPDATE_BANNERS_SUCCESS = 'UPDATE_BANNERS_SUCCESS';
export const UPDATE_BANNERS_FAIL = 'UPDATE_BANNERS_FAIL'


export const UPDATE_BANNER_ACTIVE_REQUEST = 'UPDATE_BANNER_ACTIVE_REQUEST';
export const UPDATE_BANNER_ACTIVE_SUCCESS = 'UPDATE_BANNER_ACTIVE_SUCCESS';
export const UPDATE_BANNER_ACTIVE_FAIL = 'UPDATE_BANNER_ACTIVE_FAIL';


export const DELETE_BANNER_ACTIVE_REQUEST = 'DELETE_BANNER_ACTIVE_REQUEST';
export const DELETE_BANNER_ACTIVE_SUCCESS = 'DELETE_BANNER_ACTIVE_SUCCESS';
export const DELETE_BANNER_ACTIVE_FAIL = 'DELETE_BANNER_ACTIVE_FAIL';