export const GET_ALL_CLIENT_MESSAGE_REQUEST = 'GET_ALL_CLIENT_MESSAGE_REQUEST';
export const GET_ALL_CLIENT_MESSAGE_FAIL = 'GET_ALL_CLIENT_MESSAGE_FAIL';
export const GET_ALL_CLIENT_MESSAGE_SUCCESS = 'GET_ALL_CLIENT_MESSAGE_SUCCESS';


export const GET_SINGLE_CLIENT_MESSAGE_REQUEST = 'GET_SINGLE_CLIENT_MESSAGE_REQUEST';
export const GET_SINGLE_CLIENT_MESSAGE_FAIL = 'GET_SINGLE_CLIENT_MESSAGE_FAIL';
export const GET_SINGLE_CLIENT_MESSAGE_SUCCESS = 'GET_SINGLE_CLIENT_MESSAGE_SUCCESS';


export const DELETE_CLIENT_MESSAGE_REQUEST = 'DELETE_CLIENT_MESSAGE_REQUEST';
export const DELETE_CLIENT_MESSAGE_FAIL = 'DELETE_CLIENT_MESSAGE_FAIL';
export const DELETE_CLIENT_MESSAGE_SUCCESS = 'DELETE_CLIENT_MESSAGE_SUCCESS';


export const CONTRACT_MESSAGE_REFRESH_REQUEST = 'CONTRACT_MESSAGE_REFRESH_REQUEST';