 export const SEND_GROUP_NOTIFICATION_REQUEST = 'SEND_GROUP_NOTIFICATION_REQUEST';
 export const SEND_GROUP_NOTIFICATION_SUCCESS = 'SEND_GROUP_NOTIFICATION_SUCCESS';
 export const SEND_GROUP_NOTIFICATION_FAIL = 'SEND_GROUP_NOTIFICATION_FAIL';


 export const REFRESH_NOTIFICATION_REQUEST = 'REFRESH_NOTIFICATION_REQUEST';


 export const SEND_SINGLE_NOTIFICATION_REQUEST = 'SEND_SINGLE_NOTIFICATION_REQUEST';
 export const SEND_SINGLE_NOTIFICATION_SUCCESS = 'SEND_SINGLE_NOTIFICATION_SUCCESS';
 export const SEND_SINGLE_NOTIFICATION_FAIL = 'SEND_SINGLE_NOTIFICATION_FAIL';


 export const GET_ALL_NOTIFICATION_REQUEST = 'GET_ALL_NOTIFICATION_REQUEST';
 export const  GET_ALL_NOTIFICATION_SUCCESS ='GET_ALL_NOTIFICATION_SUCCESS';
 export const GET_ALL_NOTIFICATION_FAIL = 'GET_ALL_NOTIFICATION_FAIL';


 export const GET_SINGLE_USER_NOTIFICATION_SUCCESS = 'GET_SINGLE_USER_NOTIFICATION_SUCCESS';
 export const GET_SINGLE_USER_NOTIFICATION_REQUEST = 'GET_SINGLE_USER_NOTIFICATION_REQUEST';
 export const GET_SINGLE_USER_NOTIFICATION_FAIL = 'GET_SINGLE_USER_NOTIFICATION_FAIL';