export const GET_CATEGORY_BASIC_SERVICES_REQUEST = 'GET_CATEGORY_BASIC_SERVICES_REQUEST';
export const GET_CATEGORY_BASIC_SERVICES_SUCCESS = 'GET_CATEGORY_BASIC_SERVICES_SUCCESS';
export const GET_CATEGORY_BASIC_SERVICES_FAIL = 'GET_CATEGORY_BASIC_SERVICES_FAIL';

export const GET_GET_SINGLE_SERVICES_SUCCESS = 'GET_GET_SINGLE_SERVICES_SUCCESS';
export const GET_GET_SINGLE_SERVICES_FAIL = 'GET_GET_SINGLE_SERVICES_FAIL';
export const GET_GET_SINGLE_SERVICES_REQUEST = 'GET_GET_SINGLE_SERVICES_REQUEST';

export const GET_PARENT_CATEGORY_SERVICES_REQUEST = 'GET_PARENT_CATEGORY_SERVICES_REQUEST';
export const GET_PARENT_CATEGORY_SERVICES_SUCCESS = 'GET_PARENT_CATEGORY_SERVICES_SUCCESS';
export const GET_PARENT_CATEGORY_SERVICES_FAIL = 'GET_PARENT_CATEGORY_SERVICES_FAIL';

export const GET_CATEGORY_SERVICES_SUCCESS = 'GET_CATEGORY_SERVICES_SUCCESS';
export const GET_CATEGORY_SERVICES_FAIL = 'GET_CATEGORY_SERVICES_FAIL';
export const GET_CATEGORY_SERVICES_REQUEST = 'GET_CATEGORY_SERVICES_REQUEST';

