export const STORE_BOOKING_CART_REQUEST = 'STORE_BOOKING_CART_REQUEST';
export const STORE_BOOKING_CART_SUCCESS = 'STORE_BOOKING_CART_SUCCESS';

export const REMOVE_BOOKING_CART_REQUEST = 'REMOVE_BOOKING_CART_REQUEST';
export const REMOVE_BOOKING_CART_SUCCESS = 'REMOVE_BOOKING_CART_SUCCESS';

export const PAYMENT_ADDRESS_BOOKING_CART_REQUEST = 'PAYMENT_ADDRESS_BOOKING_CART_REQUEST';
export const PAYMENT_ADDRESS_BOOKING_CART_SUCCESS = 'PAYMENT_ADDRESS_BOOKING_CART_SUCCESS'


export const FINAL_STORE_BOOKING_CART_REQUEST = 'FINAL_STORE_BOOKING_CART_REQUEST';
export const FINAL_STORE_BOOKING_CART_SUCCESS = 'FINAL_STORE_BOOKING_CART_SUCCESS';


export const GET_UNIQUE_USER_BOOKING_REQUEST = 'GET_UNIQUE_USER_BOOKING_REQUEST';
export const GET_UNIQUE_USER_BOOKING_SUCCESS = 'GET_UNIQUE_USER_BOOKING_SUCCESS';
export const GET_UNIQUE_USER_BOOKING_FAIL = 'GET_UNIQUE_USER_BOOKING_FAIL';

export const STORE_BOOKING_WORKERS_REQUEST = 'STORE_BOOKING_WORKERS_REQUEST';
export const STORE_BOOKING_WORKERS_SUCCESS = 'STORE_BOOKING_WORKERS_SUCCESS';

export const REMOVE_BEFORE_SELECT_WORKER = 'REMOVE_BEFORE_SELECT_WORKER';