export const  GET_USER_PERSONAL_BOOKING_REQUEST = 'GET_USER_PERSONAL_BOOKING_REQUEST';
export const GET_USER_PERSONAL_BOOKING_SUCCESS = 'GET_USER_PERSONAL_BOOKING_SUCCESS';
export const GET_USER_PERSONAL_BOOKING_FAIL = 'GET_USER_PERSONAL_BOOKING_FAIL';



export const USER_GIVEN_THE_REVIEWS_SUCCESS = 'USER_GIVEN_THE_REVIEWS_SUCCESS';
export const USER_GIVEN_THE_REVIEWS_REQUEST = 'USER_GIVEN_THE_REVIEWS_REQUEST';
export const USER_GIVEN_THE_REVIEWS_FAIL = 'USER_GIVEN_THE_REVIEWS_FAIL';
export const USER_GIVEN_THE_REVIEWS_REFRESH = 'USER_GIVEN_THE_REVIEWS_REFRESH';


export const USER_BOOKING_CALCEL_REQUEST = 'USER_BOOKING_CALCEL_REQUEST';
export const USER_BOOKING_CALCEL_SUCCESS = 'USER_BOOKING_CALCEL_SUCCESS';
export const USER_BOOKING_CALCEL_FAIL = 'USER_BOOKING_CALCEL_FAIL';


export const USER_BOOKING_AGAIN_REQUEST = 'USER_BOOKING_AGAIN_REQUEST';
export const USER_BOOKING_AGAIN_SUCCESS = 'USER_BOOKING_AGAIN_SUCCESS';
export const USER_BOOKING_AGAIN_FAIL = 'USER_BOOKING_AGAIN_FAIL';

export const GET_SINGLE_BOOKING_BY_ID_SUCCESS = 'GET_SINGLE_BOOKING_BY_ID_SUCCESS';
export const GET_SINGLE_BOOKING_BY_ID_REQUEST = 'GET_SINGLE_BOOKING_BY_ID_REQUEST';
export const GET_SINGLE_BOOKING_BY_ID_FAIL = 'GET_SINGLE_BOOKING_BY_ID_FAIL';