export const CREATE_SEND_OTP_CLIENT_REQUEST = 'CREATE_SEND_OTP_CLIENT_REQUEST';
export const CREATE_SEND_OTP_CLIENT_SUCCESS = 'CREATE_SEND_OTP_CLIENT_SUCCESS';
export const CREATE_SEND_OTP_CLIENT_FAIL = 'CREATE_SEND_OTP_CLIENT_FAIL';


export const CREATE_CONFRIM_CLIENT_REQUEST = 'CREATE_CONFRIM_CLIENT_REQUEST';
export const CREATE_CONFRIM_CLIENT_SUCCESS = 'CREATE_CONFRIM_CLIENT_SUCCESS';
export const CREATE_CONFRIM_CLIENT_FAIL = 'CREATE_CONFRIM_CLIENT_FAIL';

export const REFRESH_CLIENT_REQUEST = 'REFRESH_CLIENT_REQUEST';


export const GET_CLIENT_PROFILE_SUCCESS = 'GET_CLIENT_PROFILE_SUCCESS';
export const GET_CLIENT_PROFILE_REQUEST = 'GET_CLIENT_PROFILE_REQUEST';
export const GET_CLIENT_PROFILE_FAIL = 'GET_CLIENT_PROFILE_FAIL';


export const UPDATE_CLIENT_PROFILE_REQUEST = 'UPDATE_CLIENT_PROFILE_REQUEST';
export const UPDATE_CLIENT_PROFILE_SUCCESS = 'UPDATE_CLIENT_PROFILE_SUCCESS';
export const UPDATE_CLIENT_PROFILE_FAIL = 'UPDATE_CLIENT_PROFILE_FAIL';


export const SEND_MESSAGE_CLIENT_TO_ADMIN_REQUEST = 'SEND_MESSAGE_CLIENT_TO_ADMIN_REQUEST';
export const SEND_MESSAGE_CLIENT_TO_ADMIN_SUCCESS = 'SEND_MESSAGE_CLIENT_TO_ADMIN_SUCCESS';
export const SEND_MESSAGE_CLIENT_TO_ADMIN_FAIL = 'SEND_MESSAGE_CLIENT_TO_ADMIN_FAIL';
export const REFRESH_CONTRACT_MESSAGE_REQURST  = 'REFRESH_CONTRACT_MESSAGE_REQURST';

export const CLIENT_LOGOUT_REQUEST_SUCCESS = 'CLIENT_LOGOUT_REQUEST_SUCCESS';


export const FIND_SERVICE_TO_WORKERS_REQUEST = 'FIND_SERVICE_TO_WORKERS_REQUEST';
export const FIND_SERVICE_TO_WORKERS_SUCCESS = 'FIND_SERVICE_TO_WORKERS_SUCCESS';
export const FIND_SERVICE_TO_WORKERS_FAIL = 'FIND_SERVICE_TO_WORKERS_FAIL';
export const FIND_WORKERS_TO_SERVICES_REQUEST = 'FIND_WORKERS_TO_SERVICES_REQUEST';
export const FIND_WORKERS_TO_SERVICES_SUCCESS = 'FIND_WORKERS_TO_SERVICES_SUCCESS';
export const FIND_WORKERS_TO_SERVICES_FAIL = 'FIND_WORKERS_TO_SERVICES_FAIL';